// Signed-in online session (server/docs/auth-lobby-protocol.md section 2): one
// socket.io connection authenticated by auth:google or a stored auth:session token.
const ONLINE_SESSION_KEY = 'diplomacyOnlineSession'
const ONLINE_ACK_TIMEOUT = 10000
const ONLINE_REPLAY_TIMEOUT = 60000
// auth:session retries after an UNAVAILABLE ack (server busy or still connecting to its
// database, protocol doc section 7): wait these many ms before each retry, then give up.
const ONLINE_RETRY_DELAYS = [1000, 2000, 4000]
// The rules code version this page runs (options/rulesVersion.js, generated by tools/rules-manifest.js). auth:google,
// auth:session and game:open carry it; a server running other rules code acks RULES_VERSION_MISMATCH (protocol doc
// section 2.7) and the page offers a reload (showRulesVersionPanel, options/onlineLogic.js).
const ONLINE_RULES_VERSION = typeof RULES_VERSION === 'string' ? RULES_VERSION : null
// The wire protocol this page speaks (handshake auth.browserProtocol, protocol doc section 4.9). Protocol 2 (TASK-687):
// nextTurn is {gameID, endHash}, the server commits its replay of the game:action stream. A server speaking another
// protocol refuses the game events with OUTDATED_CLIENT and the page asks for a reload.
const BROWSER_PROTOCOL = 2

// Storage may be unavailable (private mode, blocked cookies); sign-in still works.
function readStoredSession() {
    try { return localStorage.getItem(ONLINE_SESSION_KEY) } catch (error) { return null }
}
function storeSession(token) {
    try { localStorage.setItem(ONLINE_SESSION_KEY, token) } catch (error) {}
}
function clearStoredSession() {
    try { localStorage.removeItem(ONLINE_SESSION_KEY) } catch (error) {}
}

// Only bounded identifiers may reach sign-in diagnostics or status text.
function onlineErrorCode(code) {
    return typeof code === 'string' && /^[A-Z][A-Z0-9_]{0,63}$/.test(code) && code.trim() === code
        ? code : 'UNKNOWN_ERROR'
}

class OnlineSession {
    constructor() {
        this.socket = null
        this.account = null
        // The lobby game on screen (game:open); re-opened after a reconnect.
        this.openGameID = null
        // The account:mergeTutorial request of the last sign-in (resolves when it settles).
        this.tutorialSync = null
        this.lastSignInError = null
        this.signInAttempt = 0
    }
    connect() {
        if (this.socket) return this.socket
        // The one online socket: the hub and every lobby game use it.
        const socket = this.socket = io(window.DIPLOMACY_SERVER || DEFAULT_ONLINE_SERVER,
            {forceNew: true, timeout: 10000, auth: {browserProtocol: BROWSER_PROTOCOL}})
        // A transport reconnect is a new server socket: authenticate it again,
        // then re-open the game on screen. A failed resume keeps the account and
        // token (unless UNAUTHENTICATED), so the next reconnect tries again.
        socket.io.on('reconnect', async () => {
            if (!this.account || !await this.resume()) return
            if (this.openGameID) this.openGame(this.openGameID)
        })
        return socket
    }
    // Resolves the ack, or {ok: false, error: 'TIMEOUT'} when none arrives within timeoutMs.
    request(event, payload, timeoutMs = ONLINE_ACK_TIMEOUT, isCurrent = () => true) {
        const socket = this.connect()
        return new Promise(resolve => {
            let settled = false
            const timer = setTimeout(() => { settled = true; resolve({ok: false, error: 'TIMEOUT'}) }, timeoutMs)
            socket.emit(event, payload, ack => {
                if (settled) return
                settled = true
                clearTimeout(timer)
                if (!isCurrent()) return resolve({ok: false, error: 'CANCELLED'})
                const reply = ack && typeof ack === 'object' && !Array.isArray(ack) && typeof ack.ok === 'boolean' ? ack : {ok: false, error: 'BAD_ACK'}
                if (reply.error === 'RULES_VERSION_MISMATCH' && typeof showRulesVersionPanel === 'function')
                    showRulesVersionPanel(reply.expected, event === 'auth:google')
                if (reply.error === 'OUTDATED_CLIENT' && typeof showOutdatedClientPanel === 'function')
                    showOutdatedClientPanel()
                resolve(reply)
            })
        })
    }
    get hasStoredSession() {
        return !!readStoredSession()
    }
    // Re-authenticates with the stored token; only UNAUTHENTICATED (invalid or expired
    // token) clears the token and the account. UNAVAILABLE is retried with backoff;
    // TIMEOUT, BAD_ACK and other failures keep both, so a later reconnect retries.
    async resume() {
        const sessionToken = readStoredSession()
        if (!sessionToken) return null
        let ack = await this.request('auth:session', {sessionToken, rulesVersion: ONLINE_RULES_VERSION})
        for (const delay of ONLINE_RETRY_DELAYS) {
            if (ack.error !== 'UNAVAILABLE') break
            await new Promise(resolve => setTimeout(resolve, delay))
            ack = await this.request('auth:session', {sessionToken, rulesVersion: ONLINE_RULES_VERSION})
        }
        if (ack.ok) {
            this.account = ack.account
            this.tutorialSync = this.syncTutorialProgress()
            return this.account
        }
        if (ack.error === 'UNAUTHENTICATED') {
            clearStoredSession()
            this.account = null
        }
        return null
    }
    cancelSignIn() {
        this.signInAttempt++
        this.lastSignInError = null
    }
    async signInWithGoogle(idToken) {
        const attempt = ++this.signInAttempt
        this.lastSignInError = null
        const fail = (source, code) => {
            if (attempt === this.signInAttempt) this.lastSignInError = {source, code}
            return null
        }
        if (typeof idToken !== 'string' || !idToken.trim())
            return fail('client-detected Google sign-in', 'GOOGLE_CREDENTIAL_MISSING')
        try {
            const ack = await this.request('auth:google', {idToken, rulesVersion: ONLINE_RULES_VERSION},
                ONLINE_ACK_TIMEOUT, () => attempt === this.signInAttempt)
            if (attempt !== this.signInAttempt) return null
            if (!ack || typeof ack !== 'object' || Array.isArray(ack) || typeof ack.ok !== 'boolean')
                return fail('protocol', 'BAD_ACK')
            if (!ack.ok) {
                const code = onlineErrorCode(ack.error)
                return fail(code === 'TIMEOUT' ? 'connection' : code === 'BAD_ACK' ? 'protocol' : 'server', code)
            }
            storeSession(ack.sessionToken)
            this.account = ack.account
            this.tutorialSync = this.syncTutorialProgress()
            return this.account
        } catch (error) {
            return fail('client', 'CLIENT_ERROR')
        }
    }
    // Unites the passed tutorials of this browser and of the account (protocol doc 2.6).
    // Not awaited by sign-in: a server without account:mergeTutorial only times out here.
    async syncTutorialProgress() {
        try {
            const ack = await this.request('account:mergeTutorial', {passed: readTutorialPassed()})
            if (ack.ok && Array.isArray(ack.passed)) mergeTutorialPassed(ack.passed)
            else console.warn('tutorial progress sync failed:', onlineErrorCode(ack.error))
        } catch (error) {
            console.warn('tutorial progress sync failed: CLIENT_ERROR')
        }
    }
    // Resolves the ack; a successful rename updates the signed-in account.
    async setNickname(nickname) {
        const ack = await this.request('account:setNickname', {nickname})
        if (ack.ok) this.account = ack.account
        return ack
    }
    // lobby:create with a host-built initial board; mapName is null for co-op.
    createLobby(board, mapName, asyncMoves = false) {
        return this.request('lobby:create', {board, mapName, asyncMoves})
    }
    joinLobby(lobbyId) {
        return this.request('lobby:join', {lobbyId})
    }
    leaveLobby(lobbyId) {
        return this.request('lobby:leave', {lobbyId})
    }
    kickFromLobby(lobbyId, accountId) {
        return this.request('lobby:kick', {lobbyId, accountId})
    }
    // game:kick: the seat-1 host removes seat playerIndex from the game (protocol doc 4.5).
    kickPlayer(gameID, playerIndex) {
        return this.request('game:kick', {gameID, playerIndex, recoveryEpoch: this.socket?.recoveryEpochs?.[gameID]})
    }
    startLobby(lobbyId) {
        return this.request('lobby:start', {lobbyId})
    }
    // game:open: the server answers with the board (playYourTurn/waitYouTurn/gameStarted), then acks.
    // autoscout: the otherSettings.autoscout preference (prefetch at turn start, protocol doc 4.2); on without settings.
    openGame(gameID) {
        this.openGameID = gameID
        return this.request('game:open', {gameID, rulesVersion: ONLINE_RULES_VERSION,
            autoscout: typeof otherSettings === 'undefined' || otherSettings.autoscout !== false})
    }
    closeGame() {
        this.openGameID = null
    }
    // game:myFinished: the account's finished games, newest first (protocol doc 4.7).
    myFinishedGames() {
        return this.request('game:myFinished', {})
    }
    // game:replay: a finished game's snapshots and turns (protocol doc 4.6); a long game's reply is large.
    replayGame(gameID) {
        return this.request('game:replay', {gameID}, ONLINE_REPLAY_TIMEOUT)
    }
}

// Status text for an account:setNickname error code.
const NICKNAME_ERROR_TEXT = {
    NICKNAME_TAKEN: 'nickname is taken',
    NICKNAME_INVALID: '3-16 letters, digits, _ or -',
}
function nicknameErrorText(error) {
    return NICKNAME_ERROR_TEXT[error] || 'could not save nickname'
}

const onlineSession = new OnlineSession()

// 'play online': the hub for a signed-in or resumable session, else the sign-in screen.
// show.hub(null) marks a pending resume; show.* return false once the user has left.
async function openOnlineSession(show) {
    if (onlineSession.account) return show.hub(onlineSession.account)
    if (onlineSession.hasStoredSession) {
        if (show.hub(null) === false) return
        const account = await onlineSession.resume()
        if (account) return show.hub(account)
    }
    show.signIn()
}
