// Generated by tools/rules-manifest.js from the rules script list (rules-manifest.json): do not edit.
// Sent as rulesVersion in auth:google, auth:session and game:open (server/docs/auth-lobby-protocol.md 2.7).
const RULES_VERSION = 'fb6c0bcd89077420a8a22782c8b0ee4b9b2461c027a17729cb19f7f3f02952a4'
