// Generated by tools/rules-manifest.js from the rules script list (rules-manifest.json): do not edit.
// Sent as rulesVersion in auth:google, auth:session and game:open (server/docs/auth-lobby-protocol.md 2.7).
const RULES_VERSION = '7298f26bc20a5234c265b8b5bd4cc747008d63d984794906685a90dae851cc0f'
