// Generated by tools/rules-manifest.js from the rules script list (rules-manifest.json): do not edit.
// Sent as rulesVersion in auth:google, auth:session and game:open (server/docs/auth-lobby-protocol.md 2.7).
const RULES_VERSION = 'ee107ea0b2418b7e54de5107e1ae6a838360fa3a9ab7b8d5ae55ab7c255be374'
